### ISSUE TITLE
Naming of submission files

### ISSUE THREAD

**Issue by lionel-spinelli** [bcm-uga/hadaca3#10]
Hello,

the submission files produced by the provided R codes has the format "%Y_%m_%d_%S". It means that only the seconds on the time are taken into account, which could bring to overwriting between submission files and issues in submission identification. 
Would it be ok to have the format with hours, minutes and seconds ?

**Comment by fchuffar** [comment]
Fixed with date_suffix including "%Y_%m_%d_%H_%M_%S"
