### ISSUE TITLE
Submission is evaluated even when prediction does not respect proportion law

### ISSUE THREAD

**Issue by lionel-spinelli** [bcm-uga/hadaca3#12]
Hello,

I am testing the behavior of the submission process against error in the produced data.

I have modified the lines returning the result in the "program" function so that the output contains a column which sum is not 1:
```
  prop[1,1] = 0.3
  return(prop)
```
The submission finished normally and provide a result. The accuracy was a little bit lower (0.7 instead of 0.72) but I think it is not normal to evaluate the result if it does not respect the laws of proportions (here the sum of proportion for each samples must be 1).

Would it be possible to  check for that before launching the evaluation and return an error if something is wrong ?

**Comment by nicomy** [comment]
Issue related and treated with the issue #11 

Ty
