### ISSUE TITLE
Unable to identify issue

### ISSUE THREAD

**Issue by lionel-spinelli** [bcm-uga/hadaca3#28]
Hello,
I have added a simple code to perform feature selection in the Program function. To run this code, I need to add the MatrxStats package.
The code runs in my docker environment but fails in the submission on codabench. 
Scoring logs reports :
```
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/app/input/res/prediction.rds', probable reason 'No such file or directory'
Execution halted
```

In the reports I have no information to understand what's wrong. I have added some text traces to follow the process but those traces are not reported in the report page neither in Logs-> Stdout tabs or elsewhere.

The last submission ID that should work is 85381.
Could you please tell me how to debug this issue ?
Thanks

Here is the piece of code I have added:

 ```
 if ( !( "matrixStats" %in% installed.packages() ) ) {
    install.packages(pkgs = "matrixStats")
  } 
 
  # Select the top feature for RNA
  require( matrixStats)
  
  cat("\nComputing Variance on RNA data")
    rna_variance = matrixStats::rowVars( mix_rna_orig)
  
  cat("\nComputing Top genes on RNA data")
    top_rna_gene = names( rna_variance)[ order( rna_variance, decreasing = TRUE)[1:1000]]
  
  mix_rna = mix_rna_orig[ top_rna_gene,]
  ref_rna = ref_rna_orig[ top_rna_gene,]
  
  # Select the top feature for methylation
  cat("\nComputing Variance on methylation data")
  met_variance = rowVars( mix_met_orig)
  
  cat("\nComputing Top features on methylation data")
  top_met_feature = names( met_variance)[ order( met_variance, decreasing = TRUE)[1:1000]]
  
  mix_met = mix_met_orig[ top_met_feature,]
  ref_met = ref_met_orig[ top_met_feature,] 
```

**Comment by lionel-spinelli** [comment]
Hello Nicolas,


thanks for your response. The problem is that there is no message in the prediction section (apart the ingestion that recapitulate some system information). The only messages are in the scoring log.


Do you want me to join the zip files provided by the "Download" but for prediction and scoring ?


Best


———————————————————————————
[1727425308686]
________________________________
De : Nicolas Homberg ***@***.***>
Envoyé : mardi 1 octobre 2024 14:28:28
À : bcm-uga/hadaca3
Cc : Lionel Spinelli; Author
Objet : Re: [bcm-uga/hadaca3] Unable to identify issue (Issue #28)


Ce mail provient de l'extérieur, restons vigilants

Hello Lionel,

Can you provide the URL of this challenge ? :)

You read the logs of the scoring program which indicate that the file prediction.rds is not found, which means that the execution of your code failed.

Can you read the logs of the prediction program ?

To access it, you can, click on your submission listed in the table under my submissions, and then go into logs and read the four different logs : "stdout, stderr, Ingestion stdout, Ingestion stderr" .

**Comment by lionel-spinelli** [comment]
Hello,


thanks for your message. Here is the URL of the competition :


https://www.codabench.org/competitions/3032/?secret_key=28767dd4-3051-4d5c-8d25-13d0922481fb#/participate-tab


My username is "spinelli"


Th submission ID is 85381


Thanks you


Best


———————————————————————————
[1727425308686]
________________________________
De : Nicolas Homberg ***@***.***>
Envoyé : jeudi 3 octobre 2024 08:21:16
À : bcm-uga/hadaca3
Cc : Lionel Spinelli; Author
Objet : Re: [bcm-uga/hadaca3] Unable to identify issue (Issue #28)


Ce mail provient de l'extérieur, restons vigilants

Can you share more details please?

* URL of the competition (we have different versions of the hadaca3 ^)
* Your username
* The submission ID ?


Thank you :)

**Comment by nicomy** [comment]
Hello Lionel, 
I have news :) 

I studied your submissions and I can read in the ingestion step : 
```
[1] "/app/ingested_program/program.R"
[1] "no program to execute, go straight to scoring step"
```

Your submission file contains : 
`submission_script.R` and should contain a file named `program.R`.

In order to create this program.R, the recommended way is to execute on your computer `submission_script.R` with the command 
`Rscript submision_script.R.`

This script will create inside a folder `submissions` two zip folders that are ready to be submitted on Codabench : 
* `Results_%date%.zip` -> that contains  `result.rds`
* `program_%date%.zip` -> that contains `program.R`. 

The second possibility (less recommended!) is to manually create  your `program.R` inside a zip file. 

Tell me if you have further problems ! 

Also there are more recent challenges here : 
[Introductory Smoothie challenge ](https://www.codabench.org/competitions/3743/?secret_key=6f226b2e-78c0-42e9-bb80-a8bdc47af475)
[Phases 2-3 of hadaca3 :  ](https://www.codabench.org/competitions/3742/?secret_key=d7080226-30d4-48f1-934d-599aa0b6ff72)


There are some other useful tutorials on these challenges !
I would recommend starting with the Smoothie challenge, because it deals with a much smaller data set :)

Have a good day, and feel free to reopen this issue if you need further assistance. 
Nico

**Comment by lionel-spinelli** [comment]
Hello,


thanks for the analysis. In fact Magalia lso told me to use the newest version of the codabench. So I have used the version : https://www.codabench.org/competitions/3742/?secret_key=d7080226-30d4-48f1-934d-599aa0b6ff72#/pages-tab


And following your instruction, it works when I submit the program.zip file generated by the submission_script.R. However, when I submit the results.zip, I have a failed result (see submission 87344 and 88850).


Thanks again and sorry to do not have correctly the tutorials.


Best


———————————————————————————
[1727425308686]
________________________________
De : Nicolas Homberg ***@***.***>
Envoyé : mardi 8 octobre 2024 11:31:52
À : bcm-uga/hadaca3
Cc : Lionel Spinelli; Author
Objet : Re: [bcm-uga/hadaca3] Unable to identify issue (Issue #28)


Ce mail provient de l'extérieur, restons vigilants

Hello Lionel,
I have news :)

I studied your submissions and I can read in the ingestion step :

[1] "/app/ingested_program/program.R"
[1] "no program to execute, go straight to scoring step"


Your submission file contains :
submission_script.R and should contain a file named program.R.

In order to create this program.R, the recommended way is to execute on your computer submission_script.R with the command
Rscript submision_script.R.

This script will create inside a folder submissions two zip folders that are ready to be submitted on Codabench :

  *   Results_%date%.zip -> that contains result.rds
  *   program_%date%.zip -> that contains program.R.

The second possibility (less recommended!) is to manually create your program.R inside a zip file.

Tell me if you have further problems !

Also there are more recent challenges here :
Introductory Smoothie challenge <https://www.codabench.org/competitions/3743/?secret_key=6f226b2e-78c0-42e9-bb80-a8bdc47af475>
Phases 2-3 of hadaca3 : <https://www.codabench.org/competitions/3742/?secret_key=d7080226-30d4-48f1-934d-599aa0b6ff72>

There are some other useful tutorials on these challenges !
I would recommend starting with the Smoothie challenge, because it deals with a much smaller data set :)

Have a good day, and feel free to reopen this issue if you need further assistance.
Nico
