### ISSUE TITLE
Enhancement request  : add meta-data information on HTML result page

### ISSUE THREAD

**Issue by lionel-spinelli** [bcm-uga/hadaca3#29]
Hello,

I would like to submit an enhancement request :

In the HTML page of result of a submission, would it be possible to add the meta-data of the submission (title, name, information...) at the beginning of the page so it will be easy to recognize which submission provide which result ?

Thanks
Best

**Comment by nicomy** [comment]
Hello again, 

This a good insight, however it seems that in the current version of Codabench/ of this Hadaca challenge, this is not feasible :/ 

Thanks you, 
Nicolas
